/**
 * Issue Report Modal
 * 
 * Allows users to generate structured bug reports from failed job results.
 * Supports:
 * - Copy to clipboard as GitHub issue markdown
 * - Future: Create GitHub issue via MCP (when connected)
 */
import { useState, useMemo } from 'react';
import type { Job } from '../../services/api';

interface IssueReportModalProps {
  job: Job;
  isOpen: boolean;
  onClose: () => void;
  githubConnected?: boolean;
}

// Close icon
const CloseIcon = () => (
  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
  </svg>
);

// Copy icon
const CopyIcon = () => (
  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184" />
  </svg>
);

// Check icon
const CheckIcon = () => (
  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
  </svg>
);

export function IssueReportModal({ job, isOpen, onClose, githubConnected = false }: IssueReportModalProps) {
  const [copied, setCopied] = useState(false);
  const [title, setTitle] = useState(`[Bug] ${job.type} agent failed: ${job.errorCode || 'Unknown error'}`);
  const [additionalContext, setAdditionalContext] = useState('');

  // Extract payload info
  const payload = job.payload as Record<string, unknown> | null;
  const owner = payload?.owner as string || 'N/A';
  const repo = payload?.repo as string || 'N/A';
  const baseBranch = payload?.baseBranch as string || 'N/A';
  const taskDescription = payload?.taskDescription as string || 'N/A';

  // Generate markdown content
  const issueMarkdown = useMemo(() => {
    const traces = job.trace as Array<{ title?: string; timestamp?: string }> | undefined;
    const lastTraces = traces?.slice(-10) || [];
    const traceLog = lastTraces.map((t) => `- ${t.title || 'Event'}`).join('\n');

    return `## Bug Report from AKIS Agent Run

**Job ID:** \`${job.id}\`
**Agent:** ${job.type}
**Status:** ${job.state}
**Timestamp:** ${new Date(job.createdAt).toISOString()}

### Repro Steps
1. Ran \`${job.type}\` agent on repository \`${owner}/${repo}\`
2. Branch: \`${baseBranch}\`
3. Task: ${taskDescription}

### Expected Behavior
Agent should complete successfully without errors.

### Actual Behavior
${job.errorMessage || job.error || 'Job failed with unknown error'}

${job.errorCode ? `**Error Code:** \`${job.errorCode}\`` : ''}

### Recent Activity Log
\`\`\`
${traceLog || 'No trace events available'}
\`\`\`

### Environment
- **AI Provider:** ${job.aiProvider || 'N/A'}
- **AI Model:** ${job.aiModel || 'N/A'}
- **Correlation ID:** ${job.correlationId || 'N/A'}
${job.mcpGatewayUrl ? `- **MCP Gateway:** ${job.mcpGatewayUrl}` : ''}

${additionalContext ? `### Additional Context\n${additionalContext}` : ''}

---
*Generated by AKIS Platform*
`;
  }, [job, owner, repo, baseBranch, taskDescription, additionalContext]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(issueMarkdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleCreateGitHubIssue = () => {
    // For now, just open GitHub new issue page with prefilled content
    const issueUrl = new URL('https://github.com/OmerYasirOnal/akis-platform-devolopment/issues/new');
    issueUrl.searchParams.set('title', title);
    issueUrl.searchParams.set('body', issueMarkdown);
    issueUrl.searchParams.set('labels', 'bug,agent-failure');
    window.open(issueUrl.toString(), '_blank');
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-ak-bg/80 backdrop-blur-sm"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Modal */}
      <div role="dialog" aria-labelledby="issue-report-title" className="relative z-10 w-full max-w-2xl max-h-[90vh] overflow-hidden rounded-2xl border border-ak-border bg-ak-surface shadow-ak-xl">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-ak-border px-6 py-4">
          <h2 id="issue-report-title" className="text-lg font-semibold text-ak-text-primary">Report Issue</h2>
          <button
            onClick={onClose}
            aria-label="Close dialog"
            className="rounded-lg p-1 text-ak-text-secondary hover:bg-ak-surface-2 hover:text-ak-text-primary transition-colors"
          >
            <CloseIcon />
          </button>
        </div>

        {/* Content */}
        <div className="overflow-y-auto p-6 max-h-[60vh]">
          {/* Title Input */}
          <div className="mb-4">
            <label className="block text-sm font-medium text-ak-text-primary mb-2">
              Issue Title
            </label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full rounded-lg border border-ak-border bg-ak-surface-2 px-3 py-2 text-sm text-ak-text-primary placeholder:text-ak-text-secondary focus:border-ak-primary focus:outline-none focus:ring-1 focus:ring-ak-primary"
            />
          </div>

          {/* Additional Context */}
          <div className="mb-4">
            <label className="block text-sm font-medium text-ak-text-primary mb-2">
              Additional Context (optional)
            </label>
            <textarea
              value={additionalContext}
              onChange={(e) => setAdditionalContext(e.target.value)}
              placeholder="Add any additional information that might help diagnose the issue..."
              rows={3}
              className="w-full rounded-lg border border-ak-border bg-ak-surface-2 px-3 py-2 text-sm text-ak-text-primary placeholder:text-ak-text-secondary focus:border-ak-primary focus:outline-none focus:ring-1 focus:ring-ak-primary resize-none"
            />
          </div>

          {/* Preview */}
          <div>
            <label className="block text-sm font-medium text-ak-text-primary mb-2">
              Issue Preview
            </label>
            <div className="rounded-lg border border-ak-border bg-ak-bg p-4 max-h-64 overflow-y-auto">
              <pre className="text-xs text-ak-text-secondary font-mono whitespace-pre-wrap">
                {issueMarkdown}
              </pre>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between gap-3 border-t border-ak-border px-6 py-4">
          <p className="text-xs text-ak-text-secondary">
            {githubConnected 
              ? 'Connected to GitHub - you can create an issue directly' 
              : 'Copy the markdown and paste it into a new GitHub issue'}
          </p>
          <div className="flex items-center gap-3">
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 rounded-lg border border-ak-border bg-ak-surface-2 px-4 py-2 text-sm font-medium text-ak-text-primary hover:bg-ak-surface transition-colors"
            >
              {copied ? <CheckIcon /> : <CopyIcon />}
              {copied ? 'Copied!' : 'Copy Markdown'}
            </button>
            <button
              onClick={handleCreateGitHubIssue}
              className="flex items-center gap-2 rounded-lg bg-ak-primary px-4 py-2 text-sm font-semibold text-[#111418] hover:brightness-110 active:brightness-95 transition-colors"
            >
              Create GitHub Issue
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default IssueReportModal;
